package com.metafactory.luminabook.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingPageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingPageAllPropertiesEquals(BookingPage expected, BookingPage actual) {
        assertBookingPageAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingPageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingPageAllUpdatablePropertiesEquals(BookingPage expected, BookingPage actual) {
        assertBookingPageUpdatableFieldsEquals(expected, actual);
        assertBookingPageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingPageAutoGeneratedPropertiesEquals(BookingPage expected, BookingPage actual) {
        assertThat(actual)
            .as("Verify BookingPage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingPageUpdatableFieldsEquals(BookingPage expected, BookingPage actual) {
        assertThat(actual)
            .as("Verify BookingPage relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingPageUpdatableRelationshipsEquals(BookingPage expected, BookingPage actual) {
        // empty method
    }
}
