package com.metafactory.luminabook.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalendarIntegrationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarIntegrationAllPropertiesEquals(CalendarIntegration expected, CalendarIntegration actual) {
        assertCalendarIntegrationAutoGeneratedPropertiesEquals(expected, actual);
        assertCalendarIntegrationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarIntegrationAllUpdatablePropertiesEquals(CalendarIntegration expected, CalendarIntegration actual) {
        assertCalendarIntegrationUpdatableFieldsEquals(expected, actual);
        assertCalendarIntegrationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarIntegrationAutoGeneratedPropertiesEquals(CalendarIntegration expected, CalendarIntegration actual) {
        assertThat(actual)
            .as("Verify CalendarIntegration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarIntegrationUpdatableFieldsEquals(CalendarIntegration expected, CalendarIntegration actual) {
        assertThat(actual)
            .as("Verify CalendarIntegration relevant properties")
            .satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
            .satisfies(a -> assertThat(a.getAccessToken()).as("check accessToken").isEqualTo(expected.getAccessToken()))
            .satisfies(a -> assertThat(a.getRefreshToken()).as("check refreshToken").isEqualTo(expected.getRefreshToken()))
            .satisfies(a ->
                assertThat(a.getExternalCalendarId()).as("check externalCalendarId").isEqualTo(expected.getExternalCalendarId())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarIntegrationUpdatableRelationshipsEquals(CalendarIntegration expected, CalendarIntegration actual) {
        // empty method
    }
}
